name: botwa
type: web
strategy:
  type: deployment
routes:
  - port: 3000
    path: /
ports:
  - port: 3000
    protocol: http
env:
  - name: NODE_ENV
    value: production
regions:
  - fra 
instance_types:
  - type: free
scaling:
  min: 0
  max: 1
  targets:
    - sleep_idle_delay:
        value: 300
health_checks:
  - grace_period: 5
    interval: 30
    timeout: 5
    restart_limit: 3
    tcp:
      port: 3000
volumes: []
